version: '3.7'

services:
   web:
    build: ./pizza/app
    command: gunicorn pizzat.wsgi:application --bind 0.0.0.0:7000
    volumes:
      - ./pizza/app/:/usr/src/app/
    expose:
      - 7000
   nginx:
    build: ./nginx
    volumes:
      - ./pizza/app/:/usr/src/app/
    ports:
      - 2000:70
    depends_on:
      - web


